backend:
  name: github
  repo: gkosev7/zabulgarskitedeca
  branch: master

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Блог"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заглавие", name: "title", widget: "string" }
      - { label: "Описание", name: "description", widget: "text" }
      - { label: "Дата на публикуване", name: "pubDate", widget: "datetime" }
      - { label: "Последна редакция", name: "updatedDate", widget: "datetime", required: false }
      - { label: "Изображение", name: "heroImage", widget: "image", required: false }
      - { label: "Съдържание", name: "body", widget: "markdown" }
